//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using Plugins.ECSPowerNetcode.Features.ManagedRpcCommands;


namespace Plugins.Generated
{
    [BurstCompile]
    public struct PluginsECSPowerNetcodeFeaturesManagedRpcCommandsManagedRpcCommandResultSerializer : IComponentData, IRpcCommandSerializer<Plugins.ECSPowerNetcode.Features.ManagedRpcCommands.ManagedRpcCommandResult>
    {
        public void Serialize(ref DataStreamWriter writer, in Plugins.ECSPowerNetcode.Features.ManagedRpcCommands.ManagedRpcCommandResult data)
        {
            writer.WriteInt((int) data.result);
        }

        public void Deserialize(ref DataStreamReader reader, ref Plugins.ECSPowerNetcode.Features.ManagedRpcCommands.ManagedRpcCommandResult data)
        {
            data.result = (int) reader.ReadInt();
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<PluginsECSPowerNetcodeFeaturesManagedRpcCommandsManagedRpcCommandResultSerializer, Plugins.ECSPowerNetcode.Features.ManagedRpcCommands.ManagedRpcCommandResult>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class PluginsECSPowerNetcodeFeaturesManagedRpcCommandsManagedRpcCommandResultRpcCommandRequestSystem : RpcCommandRequestSystem<PluginsECSPowerNetcodeFeaturesManagedRpcCommandsManagedRpcCommandResultSerializer, Plugins.ECSPowerNetcode.Features.ManagedRpcCommands.ManagedRpcCommandResult>
    {
        [BurstCompile]
        protected struct SendRpc : IJobEntityBatch
        {
            public SendRpcData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendRpc{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
}
