//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using Plugins.ECSPowerNetcode.Server.Destroying;


namespace Assembly_CSharp_firstpass.Generated
{
    [BurstCompile]
    public struct PluginsECSPowerNetcodeServerDestroyingServerNetworkEntityDestroyCommandSerializer : IComponentData, IRpcCommandSerializer<Plugins.ECSPowerNetcode.Server.Destroying.ServerNetworkEntityDestroyCommand>
    {
        public void Serialize(ref DataStreamWriter writer, in Plugins.ECSPowerNetcode.Server.Destroying.ServerNetworkEntityDestroyCommand data)
        {
            writer.WriteUInt(data.networkEntityId);
        }

        public void Deserialize(ref DataStreamReader reader, ref Plugins.ECSPowerNetcode.Server.Destroying.ServerNetworkEntityDestroyCommand data)
        {
            data.networkEntityId = (uint) reader.ReadUInt();
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<PluginsECSPowerNetcodeServerDestroyingServerNetworkEntityDestroyCommandSerializer, Plugins.ECSPowerNetcode.Server.Destroying.ServerNetworkEntityDestroyCommand>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class PluginsECSPowerNetcodeServerDestroyingServerNetworkEntityDestroyCommandRpcCommandRequestSystem : RpcCommandRequestSystem<PluginsECSPowerNetcodeServerDestroyingServerNetworkEntityDestroyCommandSerializer, Plugins.ECSPowerNetcode.Server.Destroying.ServerNetworkEntityDestroyCommand>
    {
        [BurstCompile]
        protected struct SendRpc : IJobEntityBatch
        {
            public SendRpcData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendRpc{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
}
