//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using Protocol.Players.Packets;


namespace Protocol.Generated
{
    [BurstCompile]
    public struct ProtocolPlayersPacketsServerPlayerBuilderPacketSerializer : IComponentData, IRpcCommandSerializer<Protocol.Players.Packets.ServerPlayerBuilderPacket>
    {
        public void Serialize(ref DataStreamWriter writer, in Protocol.Players.Packets.ServerPlayerBuilderPacket data)
        {
            writer.WriteInt((int) data.networkConnectionId);
            writer.WriteUInt(data.networkEntityId);
            writer.WriteUInt(data.playerId);
        }

        public void Deserialize(ref DataStreamReader reader, ref Protocol.Players.Packets.ServerPlayerBuilderPacket data)
        {
            data.networkConnectionId = (int) reader.ReadInt();
            data.networkEntityId = (uint) reader.ReadUInt();
            data.playerId = (uint) reader.ReadUInt();
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<ProtocolPlayersPacketsServerPlayerBuilderPacketSerializer, Protocol.Players.Packets.ServerPlayerBuilderPacket>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class ProtocolPlayersPacketsServerPlayerBuilderPacketRpcCommandRequestSystem : RpcCommandRequestSystem<ProtocolPlayersPacketsServerPlayerBuilderPacketSerializer, Protocol.Players.Packets.ServerPlayerBuilderPacket>
    {
        [BurstCompile]
        protected struct SendRpc : IJobEntityBatch
        {
            public SendRpcData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendRpc{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
}
