//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using Protocol.Players.Packets;


namespace Protocol.Generated
{
    [BurstCompile]
    public struct ProtocolPlayersPacketsClientPlayerLoginRequestPacketSerializer : IComponentData, IRpcCommandSerializer<Protocol.Players.Packets.ClientPlayerLoginRequestPacket>
    {
        public void Serialize(ref DataStreamWriter writer, in Protocol.Players.Packets.ClientPlayerLoginRequestPacket data)
        {
        }

        public void Deserialize(ref DataStreamReader reader, ref Protocol.Players.Packets.ClientPlayerLoginRequestPacket data)
        {
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<ProtocolPlayersPacketsClientPlayerLoginRequestPacketSerializer, Protocol.Players.Packets.ClientPlayerLoginRequestPacket>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class ProtocolPlayersPacketsClientPlayerLoginRequestPacketRpcCommandRequestSystem : RpcCommandRequestSystem<ProtocolPlayersPacketsClientPlayerLoginRequestPacketSerializer, Protocol.Players.Packets.ClientPlayerLoginRequestPacket>
    {
        [BurstCompile]
        protected struct SendRpc : IJobEntityBatch
        {
            public SendRpcData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendRpc{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
}
